---
# Set up Git configuration
- name: Prompt for Git username if not already set
  ansible.builtin.pause:
    prompt: "Please enter your Git username"
  register: git_user_name_input
  when: git_user_name is not defined

- name: Set Git username fact
  ansible.builtin.set_fact:
    git_user_name: "{{ git_user_name_input.user_input }}"
  when: git_user_name is not defined

- name: Prompt for Git email if not already set
  ansible.builtin.pause:
    prompt: "Please enter your Git user email"
  register: git_user_email_input
  when: git_user_email is not defined

- name: Set Git email fact
  ansible.builtin.set_fact:
    git_user_email: "{{ git_user_email_input.user_input }}"
  when: git_user_email is not defined

- name: Set Git user.name
  community.general.git_config:
    name: user.name
    value: "{{ git_user_name }}"
    scope: global

- name: Set Git user.email
  community.general.git_config:
    name: user.email
    value: "{{ git_user_email }}"
    scope: global

- name: Set Git color.ui
  community.general.git_config:
    name: color.ui
    value: true
    scope: global

- name: Set Git core.editor to nvim
  community.general.git_config:
    name: core.editor
    value: nvim
    scope: global
