---
- name: Install GNU utilities using Homebrew
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - autoconf
    - bash
    - binutils
    - coreutils
    - diffutils
    - findutils
    - flex
    - gawk
    - gnu-indent
    - gnu-sed
    - gnu-tar
    - gnu-which
    - gpatch
    - grep
    - gzip
    - less
    - m4
    - make
    - bison
    - tree
    - watch
    - wget
    - wdiff
